# Generated by Django 5.2.8 on 2025-12-31 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Social Politic', '사회 정치'), ('Literary Fiction', '인문'), ('Child', '아동'), ('Travel', '여행'), ('History', '역사'), ('Art', '예술'), ('Novel', '소설'), ('Poem', '시'), ('Science', '과학'), ('Fantasy', '판타지'), ('Magazine', '잡지')], default='Novel', max_length=50, verbose_name='카테고리')),
                ('sale_condition', models.CharField(choices=[('For Sale', '판매 중'), ('Reserved', '예약 중'), ('Sold Out', '판매 완료')], default='For Sale', max_length=20, verbose_name='판매 상태')),
                ('title', models.CharField(max_length=255, verbose_name='책 제목')),
                ('author', models.CharField(max_length=255, verbose_name='책 저자')),
                ('publisher', models.CharField(max_length=255, verbose_name='출판사')),
                ('condition', models.CharField(max_length=100, verbose_name='책 상태')),
                ('original_price', models.IntegerField(verbose_name='원가')),
                ('selling_price', models.IntegerField(verbose_name='판매가')),
                ('detail_info', models.TextField(verbose_name='상세 정보')),
                ('book_image', models.ImageField(blank=True, upload_to='book_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book', verbose_name='책')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
